# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.27.0"

default_platform :ios

circle_artifacts_path = ENV['CIRCLE_ARTIFACTS']

ipa_path = "#{circle_artifacts_path}/ios-sdk.ipa"
dsym_path = "#{circle_artifacts_path}/ios-sdk.app.dSYM.zip" 

platform :ios do
  before_all do
    cocoapods    
  end

  desc "Build master"
  lane :master do
    gym(
      scheme: "ios-sdk",  
      export_method: "ad-hoc",
      output_directory: ENV['CIRCLE_ARTIFACTS']
    ) # Build your app - more options available
  end

  desc "Submit a new nighly build to Hockeyapp"
  lane :nightly do
    # Push to Hockey
    markdown_type = 1
    hockey(
      api_token: ENV['HOCKEYAPP_TOKEN'],
      teams: ENV['NIGHTLY_SAMPLE_TEAM_ID'],
      notes_type: markdown_type,
      ipa: ipa_path,
      dsym: dsym_path,
      commit_sha: ENV['CIRCLE_SHA1'],
      build_server_url: ENV['CIRCLE_BUILD_URL'],
      repository_url: ENV['CIRCLE_REPOSITORY_URL'],
      notes: default_changelog
    )
  end

  desc "Returns a default changelog."
  lane :default_changelog do
    changelog = sh('git log --date=local --since="1 day ago" --pretty=oneline --abbrev-commit')
    # HAX: strip emoji from changelog
    changelog = changelog.sub(/[\u{1F300}-\u{1F6FF}]/, '')
    Actions.lane_context[SharedValues::FL_CHANGELOG] = changelog
    puts changelog
    changelog
  end

  #TBD: Might be useful to set this up to send us slack messages when builds break but only on master
  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
